### PR TITLE
Added delete apps feature

### LINKED ISSUE #144: Delete Job Apps
On clicking the delete button, the user should be prompted with an alert: "are u sure you want to delete this job app?"
And if the user clicks yes, delete the job app.

### PR DESCRIPTION
**Pull request by Jaishreebala**
Screen Shot 2021-08-13 at 11 49 26 PM
added delete  feaure
closes #144

### CODE REVIEW

**Review by adshayanB — COMMENTED** [review]
Functionality seems good, is that a good color based on our ui

**Review by adshayanB — CHANGES_REQUESTED** [review]
Should we have a better colout/ui?

**Comment by Jaishreebala** [comment]
Screen Shot 2021-08-14 at 12 12 08 AM

**Review by adshayanB — APPROVED** [review]
Love it!

**Pull request merged**
